#!/usr/bin/env python3
"""
quint-fairness-gen.py — generate the FM-9 fairness annotation for
Lifecycle.qnt.

The model's `step` action is a disjunction of dozens of individual
actions, many parameterised over MachineIds. A faithful fairness
proof would impose strong-fair on must-progress actions and weak-
fair on best-effort actions, enumerated per (action, MachineId)
pair.

Quint's TLC backend rejects fairness operators inside set
comprehensions ('Level error in applying operator $SetOfAll'); we
therefore emit explicit conjuncts.

Usage:
  python3 hack/tools/quint-fairness-gen.py > /tmp/fairness.qnt-snippet

Then paste the snippet into Lifecycle.qnt's ConvergenceFair body.
"""

# All state variable identifiers in Lifecycle.qnt.
ALL_VARS = [
    "members", "learners", "leaderAt", "currentTerm", "progress",
    "memberHealth", "phase", "failureReason", "etcdMemberRegistered",
    "kubeletReady", "tlsBootstrapped", "kubeletManifestReady",
    "nodeLocallyRegistered", "staticPodManifestsWritten",
    "kubeadmMarkedAsControlPlane", "kubeadmConfigUploaded",
    "machines", "nodeRefSet", "machineHealthLabel", "decision",
    "blockReason", "preflightBlocked", "desiredReplicas", "template",
    "desiredTemplate", "observation", "lbHealthy", "nodeReachable",
    "drainBlocked", "pdbViolatedFor", "apiserverEtcdReachable",
    "apiserverReady", "etcdCompactionInProgress",
    "criRuntimeReady", "criImagesPulled", "criPodSandboxRunning",
    "criContainersRunning", "customCondition", "webhooksAvailable",
    "mhcCacheStale", "hooksTriggered",
]

VARS_TUPLE = "all { " + ", ".join(f"{v}' = {v}" for v in ALL_VARS) + " }"

print("// Generated by hack/tools/quint-fairness-gen.py — do not edit by hand.")
print("// Engineering assumption: whenever any step action is enabled,")
print("// it eventually fires. That is exactly weakFair(step, allVars).")
print()
print("temporal ConvergenceFair =")
print("  weakFair(step, {")
for v in ALL_VARS:
    print(f"    {v},")
print("  })")
print("    implies eventually(always(HealthyControlPlane))")
