@startuml capi-tpm-authenticator

(*) --> if "Client certificate File exists" then
  -->[true] if "certificate expires in less than 10 days" then
   -->[true] "Begin kubelet client CSR process"
else
 -> [false] Return kubeconfig
 -> (*)
endif
  else
  -->[false] "Begin kubelet client CSR process"
endif


(*) --> if "Server certificate file exists" then
  -->[true] if "serving certificate is self-signed" then
  -->[true] "Begin kubelet serving CSR process"
  else
  -->[true] if "serving certificate expires in less than 10 days" then
  --> [true] "Begin kubelet serving CSR process"
  else
  -> (*)
  endif
  else
  -->[false] "Begin kubelet serving CSR process"
  endif
endif

"Begin kubelet serving CSR process" --> Persist kubelet serving certificate
  --> Restart kubelet
  --> (*)

"Begin kubelet client CSR process" --> Persist certificate
  --> Return kubeconfig
  -> (*)

@enduml
