@startuml kops-bootstrap

NodeUp -> "KopsControllerServer": InstanceIdentityDocument
note right of NodeAuthorizerClient
The client connects to a
known URL:
`_node-authorizer-internal.dns_zone_:10443`,
which is a daemonset running on
the control plane. kops uses a Route53
zone exclusive for the cluster.
end note
"NodeAuthorizerServer" -> "AWS EC2 API": DescribeInstance
"AWS EC2 API" -> "NodeAuthorizerServer": DescribeInstanceResult
note right of "NodeAuthorizerServer"
Node authorizer verifies
following:
* instance is running
* instance profile
* ip address doesn't clash
endnote
"NodeAuthorizerServer" -> "NodeAuthorizerClient": Bootstrap Token
"NodeAuthorizerClient" -> "Kubelet": Bootstrap Token
"Kubelet" -> "API Server": Create node request
"API Server" -> Kubelet: Response
@enduml
